services:
  TYPO3\CMS\Install\SystemInformation\Typo3VersionMessage:
    autowire: true
    autoconfigure: true
    public: false
    tags:
      - name: event.listener
        identifier: 'install/show-latest-errors'
        method: 'appendMessage'
        event: TYPO3\CMS\Backend\Backend\Event\SystemInformationToolbarCollectorEvent
  TYPO3\CMS\Install\Compatibility\SlotReplacement:
    autowire: true
    autoconfigure: true
    public: false
    tags:
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onLanguagePackProcessMirrorUrl'
        event: TYPO3\CMS\Install\Service\Event\ModifyLanguagePackRemoteBaseUrlEvent
